In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [8]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [159]:
import numpy as np

In [12]:
a = np.array([1,2,3,4]) 
b = np.array([2,3,4,5]) 

In [14]:
a*b

array([ 2,  6, 12, 20])

In [16]:
np.array([3.14,4,5,6])

array([3.14, 4.  , 5.  , 6.  ])

In [18]:
np.array([3.14,4,5,6],dtype='int')

array([3, 4, 5, 6])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.full((3,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [30]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [32]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [34]:
np.random.normal(10,4,(2,3))

array([[ 7.92410362,  6.41962378,  3.46871639],
       [14.2104421 ,  6.85274945, 17.10848729]])

In [36]:
# 3x3 boyutunda, ortalaması 5 ve standart sapması 2 olan normal dağılımlı sayı matrisi
arr = np.random.normal(loc=5, scale=2, size=(3, 3))
print(arr)

[[1.53680908 7.37374552 2.61125343]
 [4.31047015 7.11778791 4.01987938]
 [6.28837579 0.75255227 3.59363413]]


In [38]:
np.random.randint(0,10,(3,3))

array([[2, 4, 6],
       [0, 0, 7],
       [0, 9, 8]])

## NumPy Array Özellikleri 
* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [42]:
a= np.random.randint(10,size=10)

In [44]:
a.ndim

1

In [46]:
a.shape

(10,)

In [48]:
a.size

10

In [50]:
a.dtype

dtype('int64')

In [52]:
b= np.random.randint(10,size=(3,5))

In [54]:
b.ndim

2

In [56]:
b.shape

(3, 5)

In [58]:
b.size

15

In [60]:
b.dtype

dtype('int64')

## Yeniden Şekillendirme (reshaping)

In [77]:
a= np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [79]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
a.reshape((5,2))

ValueError: cannot reshape array of size 9 into shape (5,2)

## Birleştirme(concatenation)

In [88]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [91]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [93]:
a= np.array([[1,2,3],
             [4,5,6]])

In [95]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [100]:
x= np.array([1,2,3,99,99,3,2,1])

In [106]:
a,b,c= np.split(x,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [118]:
m= np.arange(16).reshape([4,4])
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
np.vsplit(m,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [116]:
np.hsplit(m,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Sıralama (Sorting)

In [121]:
v= np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [123]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [125]:
v

array([2, 1, 4, 3, 5])

In [129]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [133]:
a = np.array([[8, 2, 5],
              [3, 7, 1]])
a

array([[8, 2, 5],
       [3, 7, 1]])

In [135]:
sorted_rows = np.sort(a, axis=1)
print(sorted_rows)

[[2 5 8]
 [1 3 7]]


In [137]:
sorted_columns = np.sort(a, axis=0)
print(sorted_columns)

[[3 2 1]
 [8 7 5]]


In [139]:
a= np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [141]:
a[0:3]

array([20, 21, 22])

In [143]:
a[:3]

array([20, 21, 22])

In [145]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [147]:
a[1::2]

array([21, 23, 25, 27, 29])

In [153]:
m= np.random.randint(10,size=(5,5))
m

array([[2, 6, 2, 8, 1],
       [8, 9, 7, 1, 0],
       [4, 5, 1, 8, 0],
       [8, 2, 1, 1, 8],
       [9, 8, 2, 6, 4]])

In [155]:
m[:,0]

array([2, 8, 4, 8, 9])

In [157]:
m[0,:]

array([2, 6, 2, 8, 1])

In [159]:
m[0:2,0:3]

array([[2, 6, 2],
       [8, 9, 7]])

## Alt Küme Üzerinde İşlem Yapmak

In [162]:
a = np.random.randint(10, size = (5,5))
a

array([[0, 5, 7, 4, 6],
       [7, 8, 4, 2, 4],
       [0, 7, 3, 3, 6],
       [2, 2, 0, 2, 8],
       [6, 5, 4, 0, 4]])

In [164]:
alt_a = a[0:3,0:2]
alt_a

array([[0, 5],
       [7, 8],
       [0, 7]])

In [166]:
alt_a[0,0]= 99
alt_a[1,1]= 88
alt_a

array([[99,  5],
       [ 7, 88],
       [ 0,  7]])

In [168]:
a

array([[99,  5,  7,  4,  6],
       [ 7, 88,  4,  2,  4],
       [ 0,  7,  3,  3,  6],
       [ 2,  2,  0,  2,  8],
       [ 6,  5,  4,  0,  4]])

In [170]:
m = np.random.randint(10, size = (5,5))
m

array([[4, 8, 8, 0, 6],
       [4, 9, 6, 3, 8],
       [1, 7, 3, 3, 9],
       [7, 2, 8, 0, 6],
       [1, 1, 1, 9, 9]])

In [174]:
alt_m= m[0:3,0:2].copy()
alt_m

array([[4, 8],
       [4, 9],
       [1, 7]])

In [176]:
alt_m[0,0]= 99
alt_m[1,1]= 88
alt_m

array([[99,  8],
       [ 4, 88],
       [ 1,  7]])

In [178]:
m

array([[4, 8, 8, 0, 6],
       [4, 9, 6, 3, 8],
       [1, 7, 3, 3, 9],
       [7, 2, 8, 0, 6],
       [1, 1, 1, 9, 9]])

## Fancy Index ile Elemanlara Erişmek

In [181]:
v= np.arange(0,30,3)
v[1]

3

In [183]:
al_getir=[1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [187]:
m= np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [189]:
satir= np.array([0,1])
sutun= np.array([1,2])
m[satir,sutun]

array([1, 5])

In [191]:
m[0,[1,2]]

array([1, 2])

In [193]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [202]:
arr = np.array([1, 2, 3])
np.mean(arr)

2.0

In [204]:
arr.sum()

6

In [206]:
arr.min()

1

In [208]:
arr.max(axis=0)

3

In [210]:
np.var(arr)

0.6666666666666666

In [214]:
np.std(arr)

0.816496580927726

# PANDAS
## Pandas Serisi Oluşturma

In [161]:
import pandas as pd

In [223]:
seri = pd.Series([1,2,3,4,5])
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [225]:
type(seri)

pandas.core.series.Series

In [227]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [229]:
seri.dtype

dtype('int64')

In [231]:
seri.size

5

In [233]:
seri.ndim

1

In [235]:
seri.values

array([1, 2, 3, 4, 5])

In [237]:
seri.head(3)

0    1
1    2
2    3
dtype: int64

In [239]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

In [241]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [249]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])
seri

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [251]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [253]:
sozluk = pd.Series({"reg":10, "log":11, "cart":12})
sozluk

reg     10
log     11
cart    12
dtype: int64

In [255]:
pd.concat([sozluk,sozluk])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

## Eleman İşlemleri

In [260]:
a = np.array([12,23,34,45,56])
seri = pd.Series(a)
seri

0    12
1    23
2    34
3    45
4    56
dtype: int64

In [262]:
seri[0]

12

In [264]:
seri[:3]

0    12
1    23
2    34
dtype: int64

In [12]:
seri = pd.Series([121,200,150,99], index = ["reg", "loj", "cart", "rf"] )
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [14]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [18]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [20]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [22]:
seri.values

array([121, 200, 150,  99])

In [24]:
"reg" in seri

True

In [26]:
"a" in seri

False

In [28]:
seri["reg"]

121

In [30]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [32]:
seri["reg"] = 130
seri["reg"]

130

In [36]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

## Pandas Dataframe

In [39]:
l = [1,2,39,67,90]
l

[1, 2, 39, 67, 90]

In [41]:
pd.DataFrame(l, columns = ["degisken_ismi"])

,degisken_ismi
0,1
1,2
2,39
3,67
4,90


In [43]:
m =np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

,var1,var2,var3
0,1,2,3
1,4,5,6
2,7,8,9


In [47]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

,var1,var2,var3
0,1,2,3
1,4,5,6
2,7,8,9


In [49]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [51]:
df.columns = ("deg1", "deg2", "deg3")

In [53]:
df

,deg1,deg2,deg3
0,1,2,3
1,4,5,6
2,7,8,9


In [55]:
type(df)

pandas.core.frame.DataFrame

In [57]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [59]:
df.shape

(3, 3)

In [61]:
df.ndim

2

In [63]:
df.size

9

In [65]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
type(df.values)

numpy.ndarray

In [69]:
df.tail(2)

,deg1,deg2,deg3
1,4,5,6
2,7,8,9


In [71]:
a = np.array([1,2,3,4,5])

In [73]:
pd.DataFrame(a,columns = ["deg1"])

,deg1
0,1
1,2
2,3
3,4
4,5


In [103]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [105]:
sozluk = {"var1":s1, "var2":s2, "var3":s3}
sozluk

{'var1': array([9, 2, 1, 9, 4]),
 'var2': array([2, 8, 7, 5, 7]),
 'var3': array([9, 1, 3, 1, 7])}

In [107]:
df = pd.DataFrame(sozluk)
df

,var1,var2,var3
0,9,2,9
1,2,8,1
2,1,7,3
3,9,5,1
4,4,7,7


In [109]:
df[0:1]

,var1,var2,var3
0,9,2,9


In [111]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [113]:
df.index = ["a", "b", "c", "d", "e"]
df

,var1,var2,var3
a,9,2,9
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [115]:
df["c":"e"]

,var1,var2,var3
c,1,7,3
d,9,5,1
e,4,7,7


In [117]:
df.drop("a", axis = 0)

,var1,var2,var3
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [119]:
df

,var1,var2,var3
a,9,2,9
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [122]:
df.drop("a", axis = 0, inplace = True)

In [124]:
df

,var1,var2,var3
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [126]:
l = ["c","e"]

In [128]:
df.drop(l, axis=0)

,var1,var2,var3
b,2,8,1
d,9,5,1


In [130]:
"var1" in df

True

In [132]:
l = ["var1", "var4", "var2"]

In [134]:
for i in l:
    print(i in df)

True
False
True


In [136]:
df

,var1,var2,var3
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [140]:
df["var4"] = df["var1"]/df["var2"]

In [142]:
df

,var1,var2,var3,var4
b,2,8,1,0.250000
c,1,7,3,0.142857
d,9,5,1,1.800000
e,4,7,7,0.571429


In [144]:
df.drop("var4", axis=1)

,var1,var2,var3
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [146]:
df

,var1,var2,var3,var4
b,2,8,1,0.250000
c,1,7,3,0.142857
d,9,5,1,1.800000
e,4,7,7,0.571429


In [148]:
df.drop("var4", axis=1,inplace = True)

In [150]:
df

,var1,var2,var3
b,2,8,1
c,1,7,3
d,9,5,1
e,4,7,7


In [152]:
l = ["var1", "var2"]

In [154]:
df.drop(l, axis=1)

,var3
b,1
c,3
d,1
e,7


In [163]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df

,var1,var2,var3
0,14,28,4
1,18,18,12
2,26,10,5
3,16,13,10
4,13,29,22
5,6,18,16
6,2,11,26
7,13,5,21
8,24,12,9
9,24,23,16


In [165]:
df.loc[0:3]

,var1,var2,var3
0,14,28,4
1,18,18,12
2,26,10,5
3,16,13,10


In [167]:
df.iloc[0:3]

,var1,var2,var3
0,14,28,4
1,18,18,12
2,26,10,5


In [169]:
df.iloc[0,0]

14

In [171]:
df.iloc[:3,:2]

,var1,var2
0,14,28
1,18,18
2,26,10


In [173]:
df.loc[0:3,"var3"]

0     4
1    12
2     5
3    10
Name: var3, dtype: int64

In [175]:
df.iloc[0:3, 1:3]

,var2,var3
0,28,4
1,18,12
2,10,5


In [177]:
df.iloc[0:3]["var3"]

0     4
1    12
2     5
Name: var3, dtype: int64

In [179]:
df["var1"]

0    14
1    18
2    26
3    16
4    13
5     6
6     2
7    13
8    24
9    24
Name: var1, dtype: int64

In [181]:
df[0:2][["var1", "var2"]]

,var1,var2
0,14,28
1,18,18


In [183]:
df[df.var1 > 15]

,var1,var2,var3
1,18,18,12
2,26,10,5
3,16,13,10
8,24,12,9
9,24,23,16


In [185]:
df[df.var1 > 15]["var1"]

1    18
2    26
3    16
8    24
9    24
Name: var1, dtype: int64

In [189]:
df[(df.var1 > 15) & (df.var3 < 10)]

,var1,var2,var3
2,26,10,5
8,24,12,9


In [195]:
df.loc[(df.var1 > 15) & (df.var3 < 10), ["var1","var2"]]

,var1,var2
2,26,10
8,24,12


In [197]:
df[(df.var1 > 15)][["var1","var2"]]

,var1,var2
1,18,18
2,26,10
3,16,13
8,24,12
9,24,23


In [199]:
df

,var1,var2,var3
0,14,28,4
1,18,18,12
2,26,10,5
3,16,13,10
4,13,29,22
5,6,18,16
6,2,11,26
7,13,5,21
8,24,12,9
9,24,23,16


In [203]:
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df1

,var1,var2,var3
0,12,16,15
1,29,5,9
2,5,19,13
3,23,12,10
4,25,27,9


In [205]:
df2 = df1 + 99

In [207]:
df2

,var1,var2,var3
0,111,115,114
1,128,104,108
2,104,118,112
3,122,111,109
4,124,126,108


In [209]:
pd.concat([df1,df2])

,var1,var2,var3
0,12,16,15
1,29,5,9
2,5,19,13
3,23,12,10
4,25,27,9
0,111,115,114
1,128,104,108
2,104,118,112
3,122,111,109
4,124,126,108


In [211]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [213]:
pd.concat([df1,df2], ignore_index=True)

,var1,var2,var3
0,12,16,15
1,29,5,9
2,5,19,13
3,23,12,10
4,25,27,9
5,111,115,114
6,128,104,108
7,104,118,112
8,122,111,109
9,124,126,108


In [215]:
df2.columns = ["var1","var2","deg3"]

In [217]:
df2

,var1,var2,deg3
0,111,115,114
1,128,104,108
2,104,118,112
3,122,111,109
4,124,126,108


In [219]:
pd.concat([df1,df2])

,var1,var2,var3,deg3
0,12,16,15.0,NaN
1,29,5,9.0,NaN
2,5,19,13.0,NaN
3,23,12,10.0,NaN
4,25,27,9.0,NaN
0,111,115,NaN,114.0
1,128,104,NaN,108.0
2,104,118,NaN,112.0
3,122,111,NaN,109.0
4,124,126,NaN,108.0


In [221]:
pd.concat([df1,df2], join = "inner")

,var1,var2
0,12,16
1,29,5
2,5,19
3,23,12
4,25,27
0,111,115
1,128,104
2,104,118
3,122,111
4,124,126


In [227]:
df1 = pd.DataFrame({'calisanlar': ['Ali','Veli','Ayse','Fatma'],
                   'grup': ['Muhasebe','Muhendislik','Muhendislik', 'İK']})
df1

,calisanlar,grup
0,Ali,Muhasebe
1,Veli,Muhendislik
2,Ayse,Muhendislik
3,Fatma,İK


In [229]:
df2 = pd.DataFrame({'calisanlar': ['Ayse','Ali','Veli','Fatma'],
                   'ilk_giris': [1010,2009,2014,2019]})
df2

,calisanlar,ilk_giris
0,Ayse,1010
1,Ali,2009
2,Veli,2014
3,Fatma,2019


In [231]:
pd.merge(df1,df2)

,calisanlar,grup,ilk_giris
0,Ali,Muhasebe,2009
1,Veli,Muhendislik,2014
2,Ayse,Muhendislik,1010
3,Fatma,İK,2019


In [233]:
pd.merge(df1,df2, on = "calisanlar")

,calisanlar,grup,ilk_giris
0,Ali,Muhasebe,2009
1,Veli,Muhendislik,2014
2,Ayse,Muhendislik,1010
3,Fatma,İK,2019


In [237]:
df3 = pd.merge(df1,df2)
df3

,calisanlar,grup,ilk_giris
0,Ali,Muhasebe,2009
1,Veli,Muhendislik,2014
2,Ayse,Muhendislik,1010
3,Fatma,İK,2019


In [239]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik','İK'],
                   'mudur':['Caner','Mustafa','Berkcan']})
df4

,grup,mudur
0,Muhasebe,Caner
1,Muhendislik,Mustafa
2,İK,Berkcan


In [241]:
pd.merge(df3,df4)

,calisanlar,grup,ilk_giris,mudur
0,Ali,Muhasebe,2009,Caner
1,Veli,Muhendislik,2014,Mustafa
2,Ayse,Muhendislik,1010,Mustafa
3,Fatma,İK,2019,Berkcan


In [243]:
df5 = pd.DataFrame({'grup': ['Muhasebe','Muhasebe','Muhendislik', 'Muhendislik','İK', 'İK'],
                   'yetenekler':['natematik','excel','kodlama', 'linux', 'excel', 'yonetim']})
df5

,grup,yetenekler
0,Muhasebe,natematik
1,Muhasebe,excel
2,Muhendislik,kodlama
3,Muhendislik,linux
4,İK,excel
5,İK,yonetim


In [245]:
df1

,calisanlar,grup
0,Ali,Muhasebe
1,Veli,Muhendislik
2,Ayse,Muhendislik
3,Fatma,İK


In [247]:
pd.merge(df1,df5)

,calisanlar,grup,yetenekler
0,Ali,Muhasebe,natematik
1,Ali,Muhasebe,excel
2,Veli,Muhendislik,kodlama
3,Veli,Muhendislik,linux
4,Ayse,Muhendislik,kodlama
5,Ayse,Muhendislik,linux
6,Fatma,İK,excel
7,Fatma,İK,yonetim


# Gruplama ve Toplulaştırma (Grouping & Aggregation )
Basit toplulaştırma fonksiyonları:
* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [251]:
import seaborn as sns

In [255]:
df = sns.load_dataset("planets")
df

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300000,7.10,77.40,2006
1,Radial Velocity,1,874.774000,2.21,56.95,2008
2,Radial Velocity,1,763.000000,2.60,19.84,2011
3,Radial Velocity,1,326.030000,19.40,110.62,2007
4,Radial Velocity,1,516.220000,10.50,119.47,2009
...,...,...,...,...,...,...
1030,Transit,1,3.941507,NaN,172.00,2006
1031,Transit,1,2.615864,NaN,148.00,2007
1032,Transit,1,3.191524,NaN,174.00,2007
1033,Transit,1,4.125083,NaN,293.00,2008


In [257]:
df.head()

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300,7.10,77.40,2006
1,Radial Velocity,1,874.774,2.21,56.95,2008
2,Radial Velocity,1,763.000,2.60,19.84,2011
3,Radial Velocity,1,326.030,19.40,110.62,2007
4,Radial Velocity,1,516.220,10.50,119.47,2009


In [261]:
df.shape

(1035, 6)

In [267]:
df.mean(numeric_only=True)

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [269]:
df["mass"].mean()

2.6381605847953216

In [271]:
df["mass"].count()

513

In [273]:
df["mass"].min()

0.0036

In [275]:
df["mass"].max()

25.0

In [277]:
df["mass"].sum()

1353.37638

In [279]:
df["mass"].std()

3.8186166509616046

In [281]:
df["mass"].var()

14.58183312700122

In [283]:
df.describe()

,number,orbital_period,mass,distance,year
count,1035.000000,992.000000,513.000000,808.000000,1035.000000
mean,1.785507,2002.917596,2.638161,264.069282,2009.070531
std,1.240976,26014.728304,3.818617,733.116493,3.972567
min,1.000000,0.090706,0.003600,1.350000,1989.000000
25%,1.000000,5.442540,0.229000,32.560000,2007.000000
50%,1.000000,39.979500,1.260000,55.250000,2010.000000
75%,2.000000,526.005000,3.040000,178.500000,2012.000000
max,7.000000,730000.000000,25.000000,8500.000000,2014.000000


In [285]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0


In [289]:
df.dropna().describe().T 
#df.dropna() → Eksik (NaN) içeren satırları siler.

,count,mean,std,min,25%,50%,75%,max
number,498.0,1.734940,1.175720,1.0000,1.00000,1.000,2.0000,6.0
orbital_period,498.0,835.778671,1469.128259,1.3283,38.27225,357.000,999.6000,17337.5
mass,498.0,2.509320,3.636274,0.0036,0.21250,1.245,2.8675,25.0
distance,498.0,52.068213,46.596041,1.3500,24.49750,39.940,59.3325,354.0
year,498.0,2007.377510,4.167284,1989.0000,2005.00000,2009.000,2011.0000,2014.0


In [291]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'veri':[10,11,52,23,43,55]}, 
                  columns=['gruplar','veri'])
df

,gruplar,veri
0,A,10
1,B,11
2,C,52
3,A,23
4,B,43
5,C,55


In [293]:
df.groupby("gruplar")

In [295]:
df.groupby("gruplar").mean()

,veri
gruplar,
A,16.5
B,27.0
C,53.5


In [297]:
df.groupby("gruplar").sum()

,veri
gruplar,
A,33
B,54
C,107


In [299]:
df = sns.load_dataset("planets")
df.head()

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300,7.10,77.40,2006
1,Radial Velocity,1,874.774,2.21,56.95,2008
2,Radial Velocity,1,763.000,2.60,19.84,2011
3,Radial Velocity,1,326.030,19.40,110.62,2007
4,Radial Velocity,1,516.220,10.50,119.47,2009


In [301]:
df.groupby("method")

In [303]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [307]:
df.groupby("method")["orbital_period"].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,631.180000,544.217663,246.360000,438.770000,631.180000,823.590000,1016.000000
Eclipse Timing Variations,9.0,4751.644444,2499.130945,1916.250000,2900.000000,4343.500000,5767.000000,10220.000000
Imaging,12.0,118247.737500,213978.177277,4639.150000,8343.900000,27500.000000,94250.000000,730000.000000
Microlensing,7.0,3153.571429,1113.166333,1825.000000,2375.000000,3300.000000,3550.000000,5100.000000
Orbital Brightness Modulation,3.0,0.709307,0.725493,0.240104,0.291496,0.342887,0.943908,1.544929
Pulsar Timing,5.0,7343.021201,16313.265573,0.090706,25.262000,66.541900,98.211400,36525.000000
Pulsation Timing Variations,1.0,1170.000000,NaN,1170.000000,1170.000000,1170.000000,1170.000000,1170.000000
Radial Velocity,553.0,823.354680,1454.926210,0.736540,38.021000,360.200000,982.000000,17337.500000
Transit,397.0,21.102073,46.185893,0.355000,3.160630,5.714932,16.145700,331.600590


In [309]:
df.groupby("method")["orbital_period"].describe().T

method,Astrometry,Eclipse Timing Variations,Imaging,Microlensing,Orbital Brightness Modulation,Pulsar Timing,Pulsation Timing Variations,Radial Velocity,Transit,Transit Timing Variations
count,2.000000,9.000000,12.000000,7.000000,3.000000,5.000000,1.0,553.00000,397.000000,3.000000
mean,631.180000,4751.644444,118247.737500,3153.571429,0.709307,7343.021201,1170.0,823.35468,21.102073,79.783500
std,544.217663,2499.130945,213978.177277,1113.166333,0.725493,16313.265573,NaN,1454.92621,46.185893,71.599884
min,246.360000,1916.250000,4639.150000,1825.000000,0.240104,0.090706,1170.0,0.73654,0.355000,22.339500
25%,438.770000,2900.000000,8343.900000,2375.000000,0.291496,25.262000,1170.0,38.02100,3.160630,39.675250
50%,631.180000,4343.500000,27500.000000,3300.000000,0.342887,66.541900,1170.0,360.20000,5.714932,57.011000
75%,823.590000,5767.000000,94250.000000,3550.000000,0.943908,98.211400,1170.0,982.00000,16.145700,108.505500
max,1016.000000,10220.000000,730000.000000,5100.000000,1.544929,36525.000000,1170.0,17337.50000,331.600590,160.000000


In [311]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'degisken1':[10,23,33,22,11,99],
                  'degisken2':[100,253,333,262,111,969]},
                 columns = ['gruplar','degisken1','degisken2'])
df

,gruplar,degisken1,degisken2
0,A,10,100
1,B,23,253
2,C,33,333
3,A,22,262
4,B,11,111
5,C,99,969


In [315]:
df.groupby("gruplar").mean()

,degisken1,degisken2
gruplar,,
A,16.0,181.0
B,17.0,182.0
C,66.0,651.0


In [329]:
df.groupby("gruplar").aggregate(["min", "median", "max"])
# Aggregate: Birden fazla istatistiksel fonksiyonu aynı anda uygulamak için kullanılır.

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [333]:
df.groupby("gruplar").aggregate({"degisken1":"min", "degisken2":"max"})

,degisken1,degisken2
gruplar,,
A,10,262
B,11,253
C,33,969


In [335]:
#filter() fonksiyonu, bir DataFrame'den sadece belirli satırları ya da sütunları isimlerine göre seçip yeni bir DataFrame oluşturmak için kullanılır.
def filter_func(x):
    return x["degisken1"].std()>9

In [337]:
df.groupby("gruplar").filter(filter_func)

,gruplar,degisken1,degisken2
2,C,33,333
5,C,99,969


In [339]:
#transform(), her satıra veya her elemana işlem uygulayıp aynı boyutta veri döndüren bir fonksiyondur.
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [345]:
df_a = df.iloc[:,1:3]
df_a.transform(lambda x: (x-x.mean()) / x.std())

,degisken1,degisken2
0,-0.687871,-0.738461
1,-0.299074,-0.263736
2,0.000000,-0.015514
3,-0.328982,-0.235811
4,-0.657963,-0.704331
5,1.973890,1.957853


In [355]:
df = pd.DataFrame({'degisken1':[10,23,33,22,11,99],
                  'degisken2':[100,253,333,262,111,969]},
                 columns = ['degisken1','degisken2'])
df

,degisken1,degisken2
0,10,100
1,23,253
2,33,333
3,22,262
4,11,111
5,99,969


In [357]:
#apply(), DataFrame veya Series’in her bir satırı veya sütununa fonksiyon uygulamak için kullanılır.
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [359]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [361]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'veri':[10,11,52,23,43,55]}, 
                  columns=['gruplar','veri'])
df

,gruplar,veri
0,A,10
1,B,11
2,C,52
3,A,23
4,B,43
5,C,55


In [369]:
df.groupby("gruplar").apply("sum")

,veri
gruplar,
A,33
B,54
C,107


# Pivot Tablolar

In [372]:
titanic = sns.load_dataset('titanic') 
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [376]:
titanic.groupby("sex")[["survived"]].mean()

,survived
sex,
female,0.742038
male,0.188908


In [378]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

/var/folders/rn/ncp8740d1db18c72mr94nnxc0000gn/T/ipykernel_4305/2203689429.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()


survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [380]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")

/var/folders/rn/ncp8740d1db18c72mr94nnxc0000gn/T/ipykernel_4305/3583784714.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")


survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [384]:
titanic.pivot_table("survived", index = "sex", columns = "class")

/var/folders/rn/ncp8740d1db18c72mr94nnxc0000gn/T/ipykernel_4305/1992281764.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", index = "sex", columns = "class")


class,First,Second,Third
sex,,,
female,0.968085,0.921053,0.500000
male,0.368852,0.157407,0.135447


In [386]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [388]:
age = pd.cut(titanic["age"],[0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [394]:
titanic.pivot_table("survived", ["sex",age],"class")

/var/folders/rn/ncp8740d1db18c72mr94nnxc0000gn/T/ipykernel_4305/33008487.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", ["sex",age],"class")


class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [396]:
m = np.arange(1,7).reshape((3,2))
pd.DataFrame(m, columns = ["var1","var2"])


,var1,var2
0,1,2
1,3,4
2,5,6


In [398]:
seri = pd.Series([121,200,150,99])

seri.values

array([121, 200, 150,  99])